name: Conditions workflow
on: push
jobs:
    skip-or-run:
        if: ${{ github.actor == 'h-kobayashi-alt' }}    # h-kobayashi-altアカウント以外は実行をスキップ
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"